import { useQuery } from "convex/react";
import { Link } from "react-router-dom";
import { api } from "../../convex/_generated/api";
import { ArrowLeft, Clock, ChefHat, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { useLanguage } from "@/contexts/LanguageContext";

export function RecipesIndexPage() {
  const { t, lang } = useLanguage();
  const recipes = useQuery(api.publicRecipes.listRecent, { limit: 100 });

  useEffect(() => {
    document.title = lang === "fr"
      ? "Toutes les recettes IA — On Mange Quoi ?"
      : "All AI recipes — What do we eat?";
    return () => { document.title = lang === "fr" ? "On Mange Quoi ?" : "What do we eat?"; };
  }, [lang]);

  return (
    <div className="min-h-screen bg-background" data-noads="true">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-surface-border">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center gap-3">
          <Link to="/" className="text-muted-foreground hover:text-foreground transition">
            <ArrowLeft className="size-5" />
          </Link>
          <Link to="/" className="flex items-center gap-2">
            <img src="/icon-192x192.png" alt={t("appName")} className="size-7 rounded-lg" />
            <span className="font-bold text-foreground text-sm">{t("appName")}</span>
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8 space-y-8">
        <div className="text-center space-y-3">
          <h1 className="text-3xl font-bold text-foreground">
            {lang === "fr" ? "🍽️ Nos recettes IA" : "🍽️ Our AI recipes"}
          </h1>
          <p className="text-muted-foreground max-w-lg mx-auto">
            {lang === "fr"
              ? "Toutes ces recettes ont été générées par intelligence artificielle à partir d'ingrédients réels."
              : "All these recipes were generated by AI from real ingredients."}
          </p>
        </div>

        {recipes === undefined ? (
          <div className="text-center text-muted-foreground animate-pulse py-12">
            {lang === "fr" ? "Chargement des recettes…" : "Loading recipes…"}
          </div>
        ) : recipes.length === 0 ? (
          <div className="text-center py-12 space-y-4">
            <Sparkles className="size-12 text-primary mx-auto" />
            <p className="text-muted-foreground">
              {lang === "fr" ? "Les premières recettes arrivent bientôt !" : "First recipes coming soon!"}
            </p>
            <Link
              to="/"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition text-sm"
            >
              {lang === "fr" ? "Générer ma première recette →" : "Generate my first recipe →"}
            </Link>
          </div>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2">
            {recipes.map((r) => (
              <Link
                key={r._id}
                to={`/recette/${r.slug}`}
                className="group rounded-2xl border border-surface-border bg-card overflow-hidden hover:border-primary/30 transition"
              >
                <div className="aspect-[16/10] bg-muted overflow-hidden">
                  {r.imageUrl ? (
                    <img
                      src={r.imageUrl}
                      alt={r.name}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                      loading="lazy"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-primary/10 to-primary/5">
                      <span className="text-4xl">🍽️</span>
                    </div>
                  )}
                </div>
                <div className="p-4 space-y-2">
                  <h2 className="font-bold text-foreground group-hover:text-primary transition line-clamp-2">
                    {r.name}
                  </h2>
                  <p className="text-sm text-muted-foreground line-clamp-2">{r.description}</p>
                  <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Clock className="size-3" /> {r.cookingTime}
                    </span>
                    <span className="flex items-center gap-1">
                      <ChefHat className="size-3" /> {r.difficulty}
                    </span>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}

        <section className="rounded-2xl bg-gradient-to-br from-primary/10 to-primary/5 border border-primary/20 p-6 text-center space-y-3">
          <h3 className="text-lg font-bold text-foreground">
            {lang === "fr" ? "Envie d'une recette sur-mesure ?" : "Want a custom recipe?"}
          </h3>
          <p className="text-muted-foreground text-sm">
            {lang === "fr"
              ? "Prends en photo ton frigo et l'IA te génère des recettes en secondes."
              : "Take a photo of your fridge and AI generates recipes in seconds."}
          </p>
          <Link
            to="/"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition"
          >
            {lang === "fr" ? "Essayer gratuitement →" : "Try for free →"}
          </Link>
        </section>
      </main>
    </div>
  );
}
